// Generates the design-sync barrel entry (apps/desktop/.ds-entry.tsx) and the
// componentSrcMap cache from a scan of the app's source.
//
// Tau has no component-library package: the "design system" is the app's own
// React surface. The converter needs a single bundlable entry whose PascalCase
// value exports ARE the component list, so we synthesize one from every
// non-test .tsx under src/ — explicit named re-exports (never `export *`) so a
// name collision is a hard error here instead of a silently dropped component.
//
// Run via .design-sync/build.sh. Needs ts-morph, resolved through the
// .design-sync/node_modules -> ../.ds-sync/node_modules symlink (recreate it on
// a fresh clone; see NOTES.md).

import { Project, Node, ts } from 'ts-morph';
import { readFileSync, readdirSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(HERE, '..');
const PKG_DIR = join(REPO, 'apps', 'desktop');
const SRC = join(PKG_DIR, 'src');

// Files whose exports are the app itself, not design-system parts.
const FILE_EXCLUDE = new Set(['App.tsx', 'main.tsx']);
// PascalCase value exports that aren't components (GRID is a grid-pitch const).
const NAME_EXCLUDE = new Set(['App', 'GRID']);

function walk(d, out = []) {
  for (const n of readdirSync(d)) {
    const p = join(d, n);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (/\.(tsx|jsx)$/.test(n) && !/\.(test|spec|stories)\./.test(n)) out.push(p);
  }
  return out;
}

const project = new Project({
  skipAddingFilesFromTsConfig: true,
  compilerOptions: { jsx: ts.JsxEmit.Preserve, allowJs: true, skipLibCheck: true },
});

const byName = new Map(); // name -> [pkg-relative path]
const files = [];
for (const p of walk(SRC).sort()) {
  if (FILE_EXCLUDE.has(relative(SRC, p))) continue;
  const sf = project.addSourceFileAtPathIfExists(p);
  if (!sf) continue;
  const names = new Set();
  for (const [name, decls] of sf.getExportedDeclarations()) {
    const real = name === 'default'
      ? decls.map((d) => d.getName?.()).find((n) => n && n !== 'default')
      : name;
    if (!real || !/^[A-Z][A-Za-z0-9]*$/.test(real)) continue;
    if (NAME_EXCLUDE.has(real)) continue;
    if (decls.some((d) => Node.isVariableDeclaration(d) || Node.isFunctionDeclaration(d) || Node.isClassDeclaration(d))) {
      names.add(real);
    }
  }
  if (!names.size) continue;
  const rel = relative(PKG_DIR, p).split(/[\\/]/).join('/');
  files.push({ rel, names: [...names].sort() });
  for (const n of names) byName.set(n, [...(byName.get(n) ?? []), rel]);
}

const collisions = [...byName].filter(([, ps]) => ps.length > 1);
if (collisions.length) {
  for (const [n, ps] of collisions) console.error(`[COLLISION] ${n}: ${ps.join(', ')}`);
  console.error('Two source files export the same component name — the barrel cannot re-export both. Rename one, or exclude it via NAME_EXCLUDE.');
  process.exit(1);
}

const lines = [
  '// GENERATED by .design-sync/gen-entry.mjs — the design-sync barrel entry.',
  '// Not app code; nothing imports this. Regenerate with .design-sync/build.sh.',
];
for (const f of files) {
  const spec = './' + f.rel.replace(/\.(tsx|jsx)$/, '');
  lines.push(`export { ${f.names.join(', ')} } from ${JSON.stringify(spec)};`);
}
writeFileSync(join(PKG_DIR, '.ds-entry.tsx'), lines.join('\n') + '\n');

// `?raw` stubs. src/engine/bundledSubcircuits.ts imports two SPICE decks with
// Vite's `?raw` suffix; esbuild has no loader for it, so tsconfig.ds.json
// aliases those specifiers at these generated modules. Generated (not
// committed) so the text can never drift from the real .sub files.
const RAW_STUBS = [
  ['tau_deadtime_driver', 'src/engine/bundled/tau_deadtime_driver.sub'],
  ['tau_555', 'src/engine/bundled/tau_555.sub'],
];
const rawOut = join(HERE, '.cache', 'stubs', 'raw');
mkdirSync(rawOut, { recursive: true });
for (const [name, rel] of RAW_STUBS) {
  const text = readFileSync(join(PKG_DIR, rel), 'utf8');
  writeFileSync(
    join(rawOut, `${name}.ts`),
    `// GENERATED from ${rel} — verbatim text of the ?raw import.\n`
      + `export default ${JSON.stringify(text)};\n`,
  );
}

mkdirSync(join(HERE, '.cache'), { recursive: true });
const srcMap =Object.fromEntries([...byName].sort(([a], [b]) => a.localeCompare(b)).map(([n, ps]) => [n, ps[0]]));
writeFileSync(join(HERE, '.cache', 'component-src-map.json'), JSON.stringify(srcMap, null, 2) + '\n');
console.error(`gen-entry: ${files.length} files, ${byName.size} components`);
