// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, afterEach, describe, expect, it, vi } from "vitest";

// The same two mocks every App-level suite takes: keep the project store off
// its in-memory workspace seeding, and keep the assistant's local-AI polling
// out of a wiring test.
vi.mock("./project/fsBridge", async (importOriginal) => ({
  ...(await importOriginal<typeof import("./project/fsBridge")>()),
  detectFsCapability: async () => "tauri" as const,
}));
vi.mock("./lib/localAiRuntime", async (importOriginal) => ({
  ...(await importOriginal<typeof import("./lib/localAiRuntime")>()),
  isNativeDesktopApp: async () => false,
  getLocalAiStatus: async () => ({
    state: "ready" as const,
    endpoint: "http://127.0.0.1:8080/v1" as const,
    managed: true,
    installed: true,
    modelId: null,
    modelRepository: null,
    detail: "Local inference is ready.",
    presets: [],
  }),
}));

/**
 * The engine bridge, replaced at its seam rather than at Tauri's.
 *
 * jsdom has no `invoke`, so the real bridge answers `not-available` for
 * everything and a live run could never start — which would make every
 * assertion below about the *absence* of a feature. Only `startLiveSession` is
 * substituted; the frame plumbing, the poll cadence and the stop-reason mapping
 * are covered by `nativeLive`'s own suite and are not re-implemented here.
 *
 * The fake echoes the requested vector names back as the latched ones, because
 * that is the contract the real child keeps and the hook filters against it:
 * net ids are generated by `extractCircuit` and are not knowable from a test.
 */
const halt = vi.fn(async () => ({ kind: "ended" as const, ended: endedByUser() }));
const alter = vi.fn(async (_options: { instance: string; value: string }) => ({
  ok: true as const,
  value: { ...endedByUser().telemetry, running: true, stopReason: null },
}));
let onEndHook: ((outcome: { kind: "ended"; ended: ReturnType<typeof endedByUser> }) => void) | null = null;

/**
 * A run that ended of its own accord, so `resolveStopReason` keeps the ENGINE's
 * reason instead of taking Tau's intent. Used to give a finished live session a
 * stop reason no bounded run could ever produce, which is the only way to tell
 * "the transport is describing this run" from "the transport is still holding
 * the last one's sentence" apart.
 */
function endedByDivergence() {
  const base = endedByUser();
  return {
    ...base,
    engineReason: "diverged" as const,
    reason: { kind: "diverged" as const, atCircuitTime: 1e-4, detail: "timestep too small" },
    detail: "timestep too small",
    telemetry: { ...base.telemetry, stopReason: "diverged" as const },
  };
}

function endedByUser() {
  const telemetry = {
    running: false,
    wallSeconds: 0.2,
    solvedSamples: 0,
    vectorCount: 2,
    scalars: 0,
    scalarBudget: 1_000_000,
    pointsPerSecond: 0,
    deliveredSamples: 0,
    decimatedSamples: 0,
    stride: 1,
    stopReason: "halted-by-user" as const,
    stopDetail: "The live run was halted.",
    engineLog: [],
  };
  return {
    engineReason: "halted-by-user" as const,
    reason: { kind: "user-stopped" as const },
    detail: telemetry.stopDetail,
    telemetry,
    retention: { deliveredSamples: 0, decimatedSamples: 0, stride: 1, skew: 0, isWholeRun: true },
    solvedCircuitTime: 0,
  };
}

vi.mock("./engine/nativeLive", async (importOriginal) => {
  const actual = await importOriginal<typeof import("./engine/nativeLive")>();
  return {
    ...actual,
    startLiveSession: vi.fn(async (options: { names?: readonly string[]; onEnd?: (o: never) => void }) => {
      onEndHook = options.onEnd as never;
      return {
        kind: "started" as const,
        start: {
          plot: "tran1",
          vectors: [...(options.names ?? [])],
          libraryPath: "/fake/libngspice.dylib",
          telemetry: endedByUser().telemetry,
        },
        session: {
          stop: async () => {
            const outcome = await halt();
            onEndHook?.(outcome as never);
            return outcome;
          },
          alter,
        },
      };
    }),
  };
});

import App from "./App";
import { DEFAULT_WORKSPACE_ID, DEFAULT_WORKSPACE_NAME } from "./project/defaultWorkspace";
import { useProject } from "./store/useProject";
import { useSchematic } from "./store/useSchematic";
import type { SchematicComponent } from "./schematic/types";

const storage = new Map<string, string>();
Object.defineProperty(globalThis, "localStorage", {
  configurable: true,
  value: {
    getItem: (key: string) => storage.get(key) ?? null,
    setItem: (key: string, value: string) => void storage.set(key, String(value)),
    removeItem: (key: string) => void storage.delete(key),
    clear: () => storage.clear(),
  },
});
class TestResizeObserver {
  constructor(private readonly callback: ResizeObserverCallback) {}
  observe(target: Element) {
    this.callback(
      [{ target, contentRect: { width: 1440, height: 600 } } as ResizeObserverEntry],
      this as unknown as ResizeObserver,
    );
  }
  unobserve() {}
  disconnect() {}
}
Object.defineProperty(globalThis, "ResizeObserver", { configurable: true, value: TestResizeObserver });

beforeEach(() => {
  storage.clear();
  halt.mockClear();
  alter.mockClear();
  onEndHook = null;
  useSchematic.getState().newCircuit();
  useProject.setState({
    rootPath: null,
    rootName: null,
    tree: [],
    expanded: [],
    workspaceFiles: {},
    error: null,
    capability: "tauri",
  });
  Element.prototype.hasPointerCapture = () => false;
  Element.prototype.setPointerCapture = () => {};
  Element.prototype.releasePointerCapture = () => {};
});
afterEach(() => cleanup());

/** A solvable RC loop: something the deck builder will accept. */
const RC: SchematicComponent[] = [
  { id: "v1", kind: "vsource", x: -128, y: 0, rotation: 0, value: "5", label: "V1" },
  { id: "r1", kind: "resistor", x: 0, y: 0, rotation: 0, value: "1k", label: "R1" },
  { id: "c1", kind: "capacitor", x: 128, y: 0, rotation: 0, value: "100n", label: "C1" },
  { id: "gnd", kind: "ground", x: -128, y: 96, rotation: 0, value: "", label: "" },
];
const RC_WIRES = [
  { id: "w1", points: [{ x: -128, y: -32 }, { x: -128, y: -64 }, { x: -32, y: -64 }, { x: -32, y: 0 }] },
  { id: "w2", points: [{ x: 32, y: 0 }, { x: 128, y: 0 }] },
  { id: "w3", points: [{ x: 128, y: 32 }, { x: 128, y: 96 }, { x: -128, y: 96 }] },
  { id: "w4", points: [{ x: -128, y: 32 }, { x: -128, y: 96 }] },
];

/**
 * The same switched divider `App.liveControls.test.tsx` uses, and for the same
 * reason: `S1` sits at the origin so a pointer event at (0, 0) lands on its
 * body, because jsdom reports a zero-size SVG and world coordinates therefore
 * coincide with client ones.
 */
const SWITCHED: SchematicComponent[] = [
  { id: "s1", kind: "switch", x: 0, y: 0, rotation: 0, value: "open", label: "S1" },
  { id: "v1", kind: "vsource", x: -128, y: 96, rotation: 0, value: "5", label: "V1" },
  { id: "r1", kind: "resistor", x: 160, y: 0, rotation: 0, value: "1k", label: "R1" },
  { id: "gnd", kind: "ground", x: -128, y: 160, rotation: 0, value: "", label: "" },
];
const SWITCHED_WIRES = [
  { id: "w1", points: [{ x: -128, y: 128 }, { x: -128, y: 160 }] },
  { id: "w2", points: [{ x: -128, y: 64 }, { x: -128, y: 0 }, { x: -32, y: 0 }] },
  { id: "w3", points: [{ x: 32, y: 0 }, { x: 128, y: 0 }] },
  { id: "w4", points: [{ x: 192, y: 0 }, { x: 192, y: 160 }, { x: -128, y: 160 }] },
];

/**
 * The same divider with a CHANGEOVER contact, which is the whole point of it
 * being here: an SPDT is two resistors in the deck and therefore two alters,
 * and the circuit the run solves between them is the thing under test.
 */
const CHANGEOVER: SchematicComponent[] = [
  { id: "s1", kind: "spdt", x: 0, y: 0, rotation: 0, value: "nc", label: "S1" },
  { id: "v1", kind: "vsource", x: -128, y: 96, rotation: 0, value: "5", label: "V1" },
  { id: "r1", kind: "resistor", x: 160, y: -64, rotation: 0, value: "1k", label: "R1" },
  { id: "r2", kind: "resistor", x: 160, y: 64, rotation: 0, value: "2k", label: "R2" },
  { id: "gnd", kind: "ground", x: -128, y: 160, rotation: 0, value: "", label: "" },
];

async function openSimulator(
  directives: string[] = [],
  circuit: { components: SchematicComponent[]; wires: typeof RC_WIRES } = { components: RC, wires: RC_WIRES },
) {
  useProject.setState({
    rootPath: DEFAULT_WORKSPACE_ID,
    rootName: DEFAULT_WORKSPACE_NAME,
    tree: [],
    expanded: [DEFAULT_WORKSPACE_ID],
    workspaceFiles: {},
    error: null,
    capability: "none",
  });
  render(<App />);
  fireEvent.click(screen.getByRole("button", { name: "New schematic" }));
  await screen.findByRole("tab", { name: /untitled\.asc/ });
  act(() => useSchematic.setState({
    components: circuit.components,
    wires: circuit.wires,
    directives,
    past: [],
    future: [],
  }));
  fireEvent.click(screen.getByRole("button", { name: "Simulator" }));
  await screen.findByRole("group", { name: "Run transport" });
}

const mode = (name: string) =>
  screen.getByRole("radio", { name }).getAttribute("aria-checked");

/**
 * Operate the contact at the origin the way a reader does.
 *
 * Deliberately NOT `useSchematic.actuateContact`: the store call moves the part
 * but never reaches `Canvas`'s `onActuate`, and it is that callback which tells
 * App the change was an actuation rather than an edit. A test that skipped it
 * would exercise the edit branch and prove nothing about the live path.
 */
async function throwContactOnCanvas() {
  await waitFor(() => expect(document.querySelector("svg.canvas")).toBeTruthy());
  const svg = document.querySelector("svg.canvas")!;
  fireEvent.pointerDown(svg, { button: 0, clientX: 0, clientY: 0 });
  fireEvent.pointerUp(svg, { button: 0, clientX: 0, clientY: 0 });
}

/**
 * "we need the live viewer to be the default" — the user's words, and the one
 * claim in this unit that a reader can check at a glance. The other half of the
 * same requirement is that an imported LTspice file still reproduces LTspice,
 * so an authored `.tran` pre-selects the other mode at its own duration instead
 * of being silently overridden.
 */
describe("App - the run transport's default mode", () => {
  it("opens LIVE when the document authors no .tran", async () => {
    await openSimulator([]);
    expect(mode("Live: run continuously")).toBe("true");
    expect(mode("Window: run a fixed time span")).toBe("false");
    expect(screen.getByRole("group", { name: "Run transport" }).textContent)
      .toContain("Runs continuously");
  });

  it("opens WINDOW at the authored duration, visibly and editably", async () => {
    await openSimulator([".tran 5m"]);
    expect(mode("Window: run a fixed time span")).toBe("true");
    const stop = screen.getByLabelText("Run window stop time") as HTMLInputElement;
    // In the decade the file was written in, not as 0.005 — the number the
    // author typed is the number they must recognise.
    expect(stop.value).toBe("5");
    expect(screen.getByRole("group", { name: "Run transport" }).textContent)
      .toContain(".tran 5m");
  });
});

describe("App - Run becomes Stop, and leaving the simulator stops the run", () => {
  it("energises the circuit and swaps Run for Stop", async () => {
    await openSimulator([]);
    fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));

    await screen.findByRole("button", { name: "Stop this run" });
    expect(screen.queryByRole("button", { name: "Run this circuit" })).toBeNull();
    // The scope only exists once a run has produced a buffer to draw from, so
    // its presence is the observable difference between "asked" and "running".
    expect(screen.getByRole("group", { name: "Live scope" })).toBeTruthy();

    fireEvent.click(screen.getByRole("button", { name: "Stop this run" }));
    await waitFor(() => expect(halt).toHaveBeenCalledTimes(1));
    await screen.findByRole("button", { name: "Run this circuit" });
  });

  /**
   * The centralisation this unit exists to get right. Every route back to the
   * schematic goes through `leaveSimulator`, and a route that skipped it would
   * leave a solver running against a view nobody is looking at — invisible
   * until the machine gets hot. Each of these is a different call site in
   * App.tsx, so they are exercised separately rather than as one case.
   */
  const routes: [string, () => void][] = [
    ["the header's Schematic toggle", () => fireEvent.click(screen.getAllByRole("button", { name: "Schematic" })[0])],
    ["the activity rail's Explorer", () => fireEvent.click(screen.getByRole("button", { name: "Explorer" }))],
    ["the activity rail's Components", () => fireEvent.click(screen.getByRole("button", { name: "Components" }))],
  ];

  for (const [label, leave] of routes) {
    it(`halts the run when the user leaves via ${label}`, async () => {
      await openSimulator([]);
      fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));
      await screen.findByRole("button", { name: "Stop this run" });

      leave();
      await waitFor(() => expect(halt).toHaveBeenCalledTimes(1));
      expect(screen.queryByRole("group", { name: "Run transport" })).toBeNull();
    });
  }
});

/**
 * The payoff the user named: "This will allow us to actively see the plot
 * change when the user clicks a button."
 *
 * The failure this guards against is the quiet one. Every piece of the path
 * exists and imports cleanly — `planLiveActuation`, `LiveActuationQueue`,
 * `LiveSpiceSession.alter` — so a wiring mistake in App.tsx does not break a
 * build or a type; it just means the switch on the canvas moves, the schematic
 * updates, and the running circuit never hears about it. Only an assertion that
 * the engine was actually commanded can tell those two worlds apart.
 */
describe("App - operating a control reaches the running circuit", () => {
  it("alters the deck's own contact resistor instead of re-running", async () => {
    await openSimulator([], { components: SWITCHED, wires: SWITCHED_WIRES });
    fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));
    await screen.findByRole("button", { name: "Stop this run" });

    await waitFor(() => expect(document.querySelector("svg.canvas")).toBeTruthy());
    const svg = document.querySelector("svg.canvas")!;
    fireEvent.pointerDown(svg, { button: 0, clientX: 0, clientY: 0 });
    fireEvent.pointerUp(svg, { button: 0, clientX: 0, clientY: 0 });

    // The sheet moved…
    await waitFor(() =>
      expect(useSchematic.getState().components.find((c) => c.id === "s1")?.value).toContain("closed"));
    // …and so did the circuit the solver is integrating. The instance name is
    // the emitter's own (`R_S1`, resolved out of the netlist) and the value is
    // `CONTACT_CLOSED_OHMS`, byte-identical to what a restarted deck would
    // write — that identity is what makes the live circuit and a re-run agree.
    await waitFor(() => expect(alter).toHaveBeenCalledTimes(1));
    expect(alter.mock.calls[0]![0]).toMatchObject({ instance: "R_S1", value: "1m" });

    // And the run is still going: an actuation is a change to this experiment,
    // not the end of it.
    expect(screen.getByRole("button", { name: "Stop this run" })).toBeTruthy();
  });
});

/**
 * The interval between two alters, said out loud.
 *
 * Tau's bridge alters one instance per command, so a part the emitter writes as
 * two resistors cannot change atomically: the run resumes after the first alter
 * and genuinely integrates a circuit that is on neither side of the switch. For
 * an SPDT that is COM floating on two 1e12 Ω resistors for ten to twenty-five
 * milliseconds, and it is visible in the trace as a transient the schematic does
 * not account for. `planLiveActuation` has always computed the sentence for it —
 * the defect was that App asked for the plan, used its steps, and dropped the
 * disclosure on the floor, which is the silent smoothing-over AGENTS.md forbids.
 */
describe("App - the circuit a multi-device actuation leaves the run solving", () => {
  it("puts the break-before-make interval on the live controls band", async () => {
    await openSimulator([], { components: CHANGEOVER, wires: SWITCHED_WIRES });
    fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));
    await screen.findByRole("button", { name: "Stop this run" });

    await throwContactOnCanvas();

    // Two alters, break first: that ordering is what creates the interval, and
    // asserting it here is what stops this becoming a test of a string.
    await waitFor(() => expect(alter).toHaveBeenCalledTimes(2));
    expect(alter.mock.calls[0]![0]).toMatchObject({ instance: "R_S1_nc", value: "1e12" });
    expect(alter.mock.calls[1]![0]).toMatchObject({ instance: "R_S1_no", value: "1m" });

    const band = screen.getByRole("group", { name: "Live controls" });
    await waitFor(() => expect(band.textContent).toContain(
      "S1 breaks before it makes, like the real part: for a few milliseconds of the run both throws are open and COM is floating.",
    ));
  });

  /**
   * The retraction half. A plain SPST is one alter, the halt/alter/resume is
   * atomic with respect to the circuit, and `intermediate` is null — so the band
   * must say nothing rather than keep a sentence about a different control's
   * different change.
   */
  it("says nothing about an interval a single-device change does not have", async () => {
    await openSimulator([], { components: SWITCHED, wires: SWITCHED_WIRES });
    fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));
    await screen.findByRole("button", { name: "Stop this run" });

    await throwContactOnCanvas();
    await waitFor(() => expect(alter).toHaveBeenCalledTimes(1));

    expect(screen.getByRole("group", { name: "Live controls" }).textContent)
      .not.toContain("both throws are open");
  });
});

/**
 * One engine, one lease.
 *
 * ngspice is held by the live session for as long as it runs, and the Rust side
 * refuses anything else with "A live simulation is running. Stop it before
 * starting another analysis." Selecting a tab in the analysis rail IS the run
 * gesture, so without a gate up here that refusal comes back as a FAILED result
 * and is filed as this circuit's operating point — an engine's "I am busy"
 * recorded as an answer about a circuit.
 */
/** `mouseDown`, not `click`: Radix's tab activates on the pointer going down,
 *  which is the same gesture and the one the rail's own suite drives. */
const selectAnalysisTab = async (name: string) =>
  fireEvent.mouseDown(await screen.findByRole("tab", { name }), { button: 0 });

describe("App - a bounded analysis cannot jump the live run's engine lease", () => {
  it("refuses the .op tab while the circuit is energised, and says so", async () => {
    await openSimulator([], { components: SWITCHED, wires: SWITCHED_WIRES });
    fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));
    await screen.findByRole("button", { name: "Stop this run" });

    await selectAnalysisTab("Operating point (.op)");

    await screen.findByText("A live run is using the engine. Stop it before starting another analysis.");
    // Nothing was solved and nothing was filed: `.op-table` is the operating
    // point's own readout, and its absence is the difference between a refusal
    // the reader was told about and one that quietly became the answer.
    await waitFor(() => expect(document.querySelector(".op-table")).toBeNull());
    // And the refusal is about the lease, not about the run: an analysis that
    // cancelled the live session to get at the engine would be a worse bug
    // than the one this replaces.
    expect(screen.getByRole("button", { name: "Stop this run" })).toBeTruthy();
  });

  /**
   * The other half, so the gate cannot be "the tab never runs anything". With
   * no live session holding the engine, the same gesture answers.
   */
  it("answers the same tab when no live run holds the engine", async () => {
    await openSimulator([], { components: SWITCHED, wires: SWITCHED_WIRES });

    await selectAnalysisTab("Operating point (.op)");

    await waitFor(() => expect(document.querySelector(".op-table")).not.toBeNull(), { timeout: 6000 });
    expect(screen.queryByText("A live run is using the engine. Stop it before starting another analysis."))
      .toBeNull();
  });
});

/**
 * Why the run ended, when two answers race.
 *
 * Every document-navigation route (`openDocument`, `clearScratchpad`,
 * `applyAssistantCircuit`, `closeTab`) replaces the store's components and calls
 * `leaveSimulator()` in the SAME event. `stopLiveRun` records the intent
 * synchronously but `running` does not go false until the halt has round-tripped
 * through the engine, so the edit effect fires first, sees a run still in
 * flight, and used to overwrite the true reason with `circuit-edited`. The
 * document did not change and then get abandoned; it was abandoned and then
 * changed, and the reader is entitled to the reason that is true.
 */
describe("App - the reason a run ended survives the document being replaced", () => {
  it("reports leaving the simulator, not a circuit edit, when both happen at once", async () => {
    await openSimulator([], { components: SWITCHED, wires: SWITCHED_WIRES });
    fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));
    await screen.findByRole("button", { name: "Stop this run" });

    // One commit, the shape every navigation route has: leave, and replace the
    // document, before the halt can round-trip.
    act(() => {
      fireEvent.click(screen.getAllByRole("button", { name: "Schematic" })[0]);
      useSchematic.setState({ components: RC, wires: RC_WIRES, directives: [] });
    });
    await waitFor(() => expect(halt).toHaveBeenCalled());

    fireEvent.click(screen.getAllByRole("button", { name: "Simulator" })[0]);
    const transport = await screen.findByRole("group", { name: "Run transport" });
    expect(transport.textContent).toContain("Stopped — you left the simulator.");
    expect(transport.textContent).not.toContain("the circuit changed");
  });
});

/**
 * The scope belongs to the document it was solved from.
 *
 * `liveRun.ring` is created once per run and never cleared, which is right for
 * the run itself — a trace has to survive its own Stop — and wrong across
 * documents: `useLiveRun` does not know a document exists. Opening another
 * circuit and returning to the simulator therefore showed the previous one's
 * waveform under the new one's name, which is the plainest kind of silently
 * wrong reading Tau can produce.
 */
describe("App - the live trace does not outlive its document", () => {
  it("clears the scope when another circuit is opened", async () => {
    await openSimulator([], { components: SWITCHED, wires: SWITCHED_WIRES });
    fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));
    await screen.findByRole("group", { name: "Live scope" });
    fireEvent.click(screen.getByRole("button", { name: "Stop this run" }));
    await waitFor(() => expect(halt).toHaveBeenCalledTimes(1));

    // Stopping is not what clears it: the trace is the record of the run and
    // the reader is looking at it on purpose.
    expect(screen.getByRole("group", { name: "Live scope" })).toBeTruthy();

    fireEvent.click(screen.getAllByRole("button", { name: "Schematic" })[0]);
    fireEvent.click(await screen.findByRole("button", { name: "New tab" }));
    await waitFor(() => expect(screen.getAllByRole("tab", { name: /\.asc/ }).length).toBe(2));

    fireEvent.click(screen.getAllByRole("button", { name: "Simulator" })[0]);
    await screen.findByRole("group", { name: "Run transport" });
    expect(screen.queryByRole("group", { name: "Live scope" })).toBeNull();
  });
});

/**
 * The transport's status line describes the run the reader just started.
 *
 * It is shared between two mechanisms that know nothing about each other, and
 * `liveRun.status` keeps its last stop reason for the life of the hook. So a
 * bounded WINDOW run that completed perfectly used to settle back onto whatever
 * the previous LIVE session had ended with — a divergence from minutes ago,
 * attached to a run that never diverged.
 */
describe("App - a finished Window run does not restate the last live stop reason", () => {
  it("drops the live session's divergence once a bounded run has taken the line", async () => {
    await openSimulator([".tran 1m"], { components: SWITCHED, wires: SWITCHED_WIRES });
    fireEvent.click(screen.getByRole("radio", { name: "Live: run continuously" }));
    fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));
    await screen.findByRole("button", { name: "Stop this run" });

    // The engine gives up on its own, so this reason is the ENGINE's and no
    // bounded run in this app could ever produce it.
    act(() => onEndHook!({ kind: "ended", ended: endedByDivergence() } as never));
    const transport = await screen.findByRole("group", { name: "Run transport" });
    await waitFor(() => expect(transport.textContent).toContain("solution diverged"));

    fireEvent.click(screen.getByRole("radio", { name: "Window: run a fixed time span" }));
    fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));

    // Wait for the bounded run to SETTLE before reading the line. Asserting
    // while it is still in flight would pass on the synthesised "Running —"
    // phase and never reach the fallback this test exists for.
    await waitFor(() => expect(document.body.textContent).toMatch(/\d+ samples/), { timeout: 6000 });
    const transportAfter = screen.getByRole("group", { name: "Run transport" });
    expect(transportAfter.textContent).not.toContain("Running");
    expect(transportAfter.textContent).not.toContain("solution diverged");
    // Not silence either: the transport is ready for the next run, and the
    // finished one's span and warnings are the results drawer's to state.
    expect(transportAfter.textContent).toContain("Ready.");
  });
});

/**
 * Operating a switch re-solves the run that is on screen.
 *
 * `runFromTransport` builds a WINDOW run from the transport's plan — the bounds
 * the user typed — while `rerunAfterActuationRef` re-solved bare
 * `effectiveAnalysisOptions`, which is still the document's authored `.tran`.
 * Throwing a switch after a 1 ms window therefore answered a 5 ms question: the
 * axis changed under the reader, with nothing on screen saying it had.
 */
describe("App - an actuation re-solves the window the user chose", () => {
  it("keeps the transport's span instead of reverting to the authored .tran", async () => {
    await openSimulator([".tran 5m"], { components: SWITCHED, wires: SWITCHED_WIRES });
    // The field reads in the decade the file was written in, so "1" here is
    // 1 ms against the authored 5 ms.
    fireEvent.change(screen.getByLabelText("Run window stop time"), { target: { value: "1" } });
    fireEvent.click(screen.getByRole("button", { name: "Run this circuit" }));

    const span = () => document.body.textContent?.match(/(\d[\d.]*)\s*(m?s)\s*·\s*\d+ samples/)?.[0] ?? null;
    await waitFor(() => expect(span()).toMatch(/^1 ms/), { timeout: 6000 });

    await waitFor(() => expect(document.querySelector("svg.canvas")).toBeTruthy());
    const svg = document.querySelector("svg.canvas")!;
    fireEvent.pointerDown(svg, { button: 0, clientX: 0, clientY: 0 });
    fireEvent.pointerUp(svg, { button: 0, clientX: 0, clientY: 0 });
    await waitFor(() =>
      expect(useSchematic.getState().components.find((c) => c.id === "s1")?.value).toContain("closed"));

    // Settled on the re-solve, not merely not-yet-changed: the sample count
    // moves because the contact did, while the span must not.
    await waitFor(() => expect(span()).toMatch(/^1 ms/), { timeout: 6000 });
    await new Promise((resolve) => setTimeout(resolve, 250));
    expect(span()).toMatch(/^1 ms/);
  });
});
